name: kun_rejasi
description: Bismillah.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  syncfusion_flutter_datepicker: ^21.1.37
  sqflite: ^2.0.2+1
  path_provider: ^2.0.8
  provider: ^6.0.2
  shared_preferences: ^2.0.18
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/logo/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
